"""v2

Revision ID: 577d561a237e
Revises: 370c632bf65b
Create Date: 2022-10-14 01:08:25.357565

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '577d561a237e'
down_revision = '370c632bf65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_active')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('profiles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
